// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Quiz.Api.Data;

#nullable disable

namespace Quiz.Api.Migrations
{
    [DbContext(typeof(QuizContext))]
    [Migration("20240827025044_SeedQuizData")]
    partial class SeedQuizData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Quiz.Api.Models.QuestionEntity", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionId"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuizId")
                        .HasColumnType("int");

                    b.HasKey("QuestionId");

                    b.HasIndex("QuizId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            QuestionId = 1,
                            Answer = "Metro Manila",
                            Question = "What is the capital of Philippines?",
                            QuizId = 1
                        },
                        new
                        {
                            QuestionId = 2,
                            Answer = "Russia",
                            Question = "Which country has the largest land area?",
                            QuizId = 1
                        },
                        new
                        {
                            QuestionId = 3,
                            Answer = "Nile",
                            Question = "What is the longest river in the world?",
                            QuizId = 1
                        },
                        new
                        {
                            QuestionId = 4,
                            Answer = "Africa",
                            Question = "Which continent is known as the 'Dark Continent'?",
                            QuizId = 1
                        },
                        new
                        {
                            QuestionId = 5,
                            Answer = "Vatican City",
                            Question = "What is the smallest country in the world?",
                            QuizId = 1
                        },
                        new
                        {
                            QuestionId = 6,
                            Answer = "George Washington",
                            Question = "Who was the first President of the United States?",
                            QuizId = 2
                        },
                        new
                        {
                            QuestionId = 7,
                            Answer = "1945",
                            Question = "In which year did World War II end?",
                            QuizId = 2
                        },
                        new
                        {
                            QuestionId = 8,
                            Answer = "Christopher Columbus",
                            Question = "Who discovered America?",
                            QuizId = 2
                        },
                        new
                        {
                            QuestionId = 9,
                            Answer = "Mayflower",
                            Question = "What was the name of the ship that brought the Pilgrims to America?",
                            QuizId = 2
                        },
                        new
                        {
                            QuestionId = 10,
                            Answer = "Neil Armstrong",
                            Question = "Who was the first man to step on the moon?",
                            QuizId = 2
                        },
                        new
                        {
                            QuestionId = 11,
                            Answer = "H2O",
                            Question = "What is the chemical symbol for water?",
                            QuizId = 3
                        },
                        new
                        {
                            QuestionId = 12,
                            Answer = "Mars",
                            Question = "What planet is known as the Red Planet?",
                            QuizId = 3
                        },
                        new
                        {
                            QuestionId = 13,
                            Answer = "Diamond",
                            Question = "What is the hardest natural substance on Earth?",
                            QuizId = 3
                        },
                        new
                        {
                            QuestionId = 14,
                            Answer = "299,792,458 meters per second",
                            Question = "What is the speed of light?",
                            QuizId = 3
                        },
                        new
                        {
                            QuestionId = 15,
                            Answer = "Skin",
                            Question = "What is the largest organ in the human body?",
                            QuizId = 3
                        },
                        new
                        {
                            QuestionId = 16,
                            Answer = "3.14",
                            Question = "What is the value of Pi to two decimal places?",
                            QuizId = 4
                        },
                        new
                        {
                            QuestionId = 17,
                            Answer = "8",
                            Question = "What is the square root of 64?",
                            QuizId = 4
                        },
                        new
                        {
                            QuestionId = 18,
                            Answer = "πr²",
                            Question = "What is the formula for the area of a circle?",
                            QuizId = 4
                        },
                        new
                        {
                            QuestionId = 19,
                            Answer = "180 degrees",
                            Question = "What is the sum of the angles in a triangle?",
                            QuizId = 4
                        },
                        new
                        {
                            QuestionId = 20,
                            Answer = "A series of numbers where each number is the sum of the two preceding ones",
                            Question = "What is the Fibonacci sequence?",
                            QuizId = 4
                        },
                        new
                        {
                            QuestionId = 21,
                            Answer = "William Shakespeare",
                            Question = "Who wrote 'Romeo and Juliet'?",
                            QuizId = 5
                        },
                        new
                        {
                            QuestionId = 22,
                            Answer = "Genesis",
                            Question = "What is the first book of the Bible?",
                            QuizId = 5
                        },
                        new
                        {
                            QuestionId = 23,
                            Answer = "Jane Austen",
                            Question = "Who wrote 'Pride and Prejudice'?",
                            QuizId = 5
                        },
                        new
                        {
                            QuestionId = 24,
                            Answer = "J.K. Rowling",
                            Question = "Who is the author of 'Harry Potter' series?",
                            QuizId = 5
                        },
                        new
                        {
                            QuestionId = 25,
                            Answer = "In Search of Lost Time by Marcel Proust",
                            Question = "What is the longest novel ever written?",
                            QuizId = 5
                        },
                        new
                        {
                            QuestionId = 26,
                            Answer = "Soccer",
                            Question = "What sport is known as the 'king of sports'?",
                            QuizId = 6
                        },
                        new
                        {
                            QuestionId = 27,
                            Answer = "9",
                            Question = "How many players are there in a baseball team?",
                            QuizId = 6
                        },
                        new
                        {
                            QuestionId = 28,
                            Answer = "300",
                            Question = "What is the highest score in a single game of bowling?",
                            QuizId = 6
                        },
                        new
                        {
                            QuestionId = 29,
                            Answer = "Brazil",
                            Question = "Which country has won the most World Cups in soccer?",
                            QuizId = 6
                        },
                        new
                        {
                            QuestionId = 30,
                            Answer = "Lacrosse",
                            Question = "What is the national sport of Canada?",
                            QuizId = 6
                        },
                        new
                        {
                            QuestionId = 31,
                            Answer = "Michael Jackson",
                            Question = "Who is known as the 'King of Pop'?",
                            QuizId = 7
                        },
                        new
                        {
                            QuestionId = 32,
                            Answer = "Soprano",
                            Question = "What is the highest female voice type?",
                            QuizId = 7
                        },
                        new
                        {
                            QuestionId = 33,
                            Answer = "Antonio Vivaldi",
                            Question = "Who composed the 'Four Seasons'?",
                            QuizId = 7
                        },
                        new
                        {
                            QuestionId = 34,
                            Answer = "Please Please Me",
                            Question = "What is the name of the Beatles' first album?",
                            QuizId = 7
                        },
                        new
                        {
                            QuestionId = 35,
                            Answer = "Mick Jagger",
                            Question = "Who is the lead singer of the Rolling Stones?",
                            QuizId = 7
                        },
                        new
                        {
                            QuestionId = 36,
                            Answer = "James Cameron",
                            Question = "Who directed 'Titanic'?",
                            QuizId = 8
                        },
                        new
                        {
                            QuestionId = 37,
                            Answer = "Avatar",
                            Question = "What is the highest-grossing film of all time?",
                            QuizId = 8
                        },
                        new
                        {
                            QuestionId = 38,
                            Answer = "Heath Ledger",
                            Question = "Who played the Joker in 'The Dark Knight'?",
                            QuizId = 8
                        },
                        new
                        {
                            QuestionId = 39,
                            Answer = "Frodo Baggins",
                            Question = "What is the name of the hobbit played by Elijah Wood in 'The Lord of the Rings'?",
                            QuizId = 8
                        },
                        new
                        {
                            QuestionId = 40,
                            Answer = "Quentin Tarantino",
                            Question = "Who directed 'Pulp Fiction'?",
                            QuizId = 8
                        },
                        new
                        {
                            QuestionId = 41,
                            Answer = "Bill Gates",
                            Question = "Who is the founder of Microsoft?",
                            QuizId = 9
                        },
                        new
                        {
                            QuestionId = 42,
                            Answer = "HyperText Transfer Protocol",
                            Question = "What does 'HTTP' stand for?",
                            QuizId = 9
                        },
                        new
                        {
                            QuestionId = 43,
                            Answer = "ENIAC",
                            Question = "What is the name of the first electronic general-purpose computer?",
                            QuizId = 9
                        },
                        new
                        {
                            QuestionId = 44,
                            Answer = "2007",
                            Question = "What year was the first iPhone released?",
                            QuizId = 9
                        },
                        new
                        {
                            QuestionId = 45,
                            Answer = "Central Processing Unit",
                            Question = "What does 'CPU' stand for?",
                            QuizId = 9
                        },
                        new
                        {
                            QuestionId = 46,
                            Answer = "Leonardo da Vinci",
                            Question = "Who painted the Mona Lisa?",
                            QuizId = 10
                        },
                        new
                        {
                            QuestionId = 47,
                            Answer = "Origami",
                            Question = "What is the art of paper folding called?",
                            QuizId = 10
                        },
                        new
                        {
                            QuestionId = 48,
                            Answer = "Michelangelo",
                            Question = "Who painted the ceiling of the Sistine Chapel?",
                            QuizId = 10
                        },
                        new
                        {
                            QuestionId = 49,
                            Answer = "Mona Lisa",
                            Question = "What is the most famous painting in the Louvre?",
                            QuizId = 10
                        },
                        new
                        {
                            QuestionId = 50,
                            Answer = "Vincent van Gogh",
                            Question = "Who is the artist behind 'The Starry Night'?",
                            QuizId = 10
                        });
                });

            modelBuilder.Entity("Quiz.Api.Models.QuizEntity", b =>
                {
                    b.Property<int>("QuizId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuizId"));

                    b.Property<string>("QuizName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("QuizId");

                    b.ToTable("Quiz");

                    b.HasData(
                        new
                        {
                            QuizId = 1,
                            QuizName = "Geography"
                        },
                        new
                        {
                            QuizId = 2,
                            QuizName = "History"
                        },
                        new
                        {
                            QuizId = 3,
                            QuizName = "Science"
                        },
                        new
                        {
                            QuizId = 4,
                            QuizName = "Math"
                        },
                        new
                        {
                            QuizId = 5,
                            QuizName = "Literature"
                        },
                        new
                        {
                            QuizId = 6,
                            QuizName = "Sports"
                        },
                        new
                        {
                            QuizId = 7,
                            QuizName = "Music"
                        },
                        new
                        {
                            QuizId = 8,
                            QuizName = "Movies"
                        },
                        new
                        {
                            QuizId = 9,
                            QuizName = "Technology"
                        },
                        new
                        {
                            QuizId = 10,
                            QuizName = "Art"
                        });
                });

            modelBuilder.Entity("Quiz.Api.Models.UsersEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1b3d5ad6-f7cf-4c90-83c6-b90e88c1196e"),
                            Password = "admin",
                            Role = "admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = new Guid("47fec716-d074-4d63-912b-947a7015fc87"),
                            Password = "user",
                            Role = "user",
                            Username = "user"
                        });
                });

            modelBuilder.Entity("Quiz.Api.Models.QuestionEntity", b =>
                {
                    b.HasOne("Quiz.Api.Models.QuizEntity", "Quiz")
                        .WithMany("Questions")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("Quiz.Api.Models.QuizEntity", b =>
                {
                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
